### ISSUE TITLE
Promotions don't go through to paypal

### ISSUE THREAD

**Issue by jescalan** [spree-contrib/spree_paypal_express#63]
When you are on the payment page and enter a promotion, then check out with paypal, the promotion is not showing up in the paypal price. This is on Spree 1.0

**Comment by radar** [comment]
Could you please submit a patch that would fix this issue?

**Comment by JDutil** [comment]
I believe the issue your having is related to https://github.com/spree/spree_paypal_express/issues/92 which has been fixed.  The issue was the promotion code form needed to be submitted before the paypal image was clicked on.

You can open a new issue if you still experience problems after the update.
